### ISSUE TITLE
Extension not working for Lightning version of Saleforce

### ISSUE THREAD

**Issue by prasannakumar312** [motiko/sfdc-debug-logs#11]
The Apex Debugger extension doesn't work for lightning version.  The Salesforce debug logs remains as is. Any resolution for this?

Thanks!

**Comment by motiko** [comment]
Can you provide replication steps?
Sorry i haven't used it in a while, i need some help with reproducing it.

**Comment by prasannakumar312** [comment]
Thanks for your response Motiko.
Steps to  Reproduce:
1. Install the Extension
2.  Login to Salesforce
3. Open any debug logs
You won't be seeing the logs in the desired extension format. Let me know if you need anything.
Thanks!

**Comment by motiko** [comment]
Sorry I cant reproduce this. Please provide more info. (console output, screenshots, urls )
