### ISSUE TITLE
Extension doesn't work on .*force.com URL's

### ISSUE THREAD

**Issue by morco4949** [motiko/sfdc-debug-logs#18]
first of all - thanks for this great extension. As an SFDC employee, I find it very useful. 

Right now, the extension's manifest doesn't support .*force.com domains and relevant scripts aren't being injected. For each URL pattern in the manifest, there should be another option for *.force.com. For example:
`
"matches": [
        "https://*.salesforce.com/p/setup/layout/ApexDebugLogDetailEdit/*"
      ]
`
this needs to change to 
`
"matches": [
        "https://*.force.com/p/setup/layout/ApexDebugLogDetailEdit/*",
        "https://*.salesforce.com/p/setup/layout/ApexDebugLogDetailEdit/*"
      ]
` 

I changed that locally on my computer and it seems to be working just fine. To make things easier, I'm attaching the revised manifest file

Thanks in advance for helping out with that
[manifest.json.zip](https://github.com/motiko/sfdc-debug-logs/files/6446221/manifest.json.zip)

**Comment by motiko** [comment]
Hi Mor,
Thank you for submitting this. Highly appreciated.
Would you want to create PR for this?

**Comment by motiko** [comment]
Ok nvm I've added in version 0.7.12
Will be published soon (in review by google now)
Thanks again for submitting this.
Say hi to the guys at click/sfdc I miss our days together.

**Comment by morco4949** [comment]
Thank you! very much appreciated
