### ISSUE TITLE
Love this extension, but it just seems to have disappeared

### ISSUE THREAD

**Issue by rodgersjosh** [motiko/sfdc-debug-logs#23]
in all honesty, I am not sure why it is now not showing.  I usually open by SF Debug logs page, and it is there.  I attempted to remove, reinstall, and restart chrome but still no luck.
Would love to get this going again.  It is a must have tool!

**Comment by motiko** [comment]
i would need some reproduction steps to work on this.

**Comment by motiko** [comment]
Feel free to reopen with reproduction steps or contact me by mail or twitter
