### ISSUE TITLE
Shift+W already mapped by Salesforce for clearing Tabs

### ISSUE THREAD

**Issue by bigkemp** [motiko/sfdc-debug-logs#27]
Issue:
Shift+W redirect to Extension's Log Tool page which interfere when a person wants to clear Tabs in Lightning.

Suggested Solutions: 
1) Add the the shortcut to the editable shortcuts in the extension

**Comment by motiko** [comment]
Thanks for opening an issue. I will fix this soon.

**Comment by motiko** [comment]
I added the option to remap 'Shift+w' in latest version 0.7.14
see commit 0be516955893be4ebfe787870f352340189c70ff
