### ISSUE TITLE
New Setup Domain is not in extension's allowlist

### ISSUE THREAD

**Issue by ori-sweep** [motiko/sfdc-debug-logs#38]
Salesforce added '-setup' to the url as they are now hosting the setup on new domains
[https://help.salesforce.com/s/articleView?id=release-notes.rn_general_setup_domain_prepare.htm&release=246&type=5](url)
[https://help.salesforce.com/s/articleView?id=001395243&type=1](url)

for example:
https://miso-hello-995-dev-ed.scratch.my.salesforce-setup.com/lightning/setup/SetupOneHome/home

@motiko help!

**Comment by motiko** [comment]
Hey, thanks for opening. Have to admit I did not actively maintain this but lets try to find a solution. 
Do I understand correctly the change that is required here is to add 
`salesforce-setup.com` for trusted domains?
And if so how can I test this?

**Comment by ori-sweep** [comment]
Yes, I suppose this is the solution.
Salesforce are moving gradually so not all scratch orgs have this domain yet. I'll try to create one.

**Comment by motiko** [comment]
If you already have access to one and can confirm it works with changes from pr #39
I would publish soon after

**Comment by motiko** [comment]
@ori-sweep Did you manage to get an org with the new domain? I would like to test before publishing

**Comment by ori-sweep** [comment]
Sorry for the delay, try this one:
https://agility-site-2390-dev-ed.scratch.my.salesforce.com/secur/frontdoor.jsp?sid=00DKO000000LEkz!AQkAQKWyOLNBNRNE4BCWX1KC.qIo0LS7ceoJlUrfV.t56Fs3F.UC_im.2f3CaBChcxyW0phLiUkJ5COJXdMKeoTIjOzB64Wb

**Comment by motiko** [comment]
The link worked when you posted it.
But I just get to it now and the link does not work anymore (probably expired session) 🤦
Anyway you send me another?

**Comment by ori-sweep** [comment]
use these creds:

test-mwwfjmufk8qk@example.com
zcozjvSqf4|u

**Comment by motiko** [comment]
Seems like it works. At least the basic functionality is there. Thanks for submitting <3
I've published the fix it should be there in version 0.7.17
Will take some time the review etc.

**Comment by ori-sweep** [comment]
Works great! Thank you!
