### ISSUE TITLE
configure hotkeys

### ISSUE THREAD

**Issue by AziEI** [motiko/sfdc-debug-logs#5]
Hi!
Hotkeys to the pages are very useful BUT - when I want to type i.e. "D letter" - I press shift+D and the extension opens new tab with debug logs :( Is it possible to configure hotkeys and turn on/off them? Would be very useful!

**Comment by motiko** [comment]
If you type it in a textbox it shouldn't open  a new tab, can you provide more specific reproduction for this ?

**Comment by AziEI** [comment]
It appears only when I work with "Flow". Tried on two diffrenet PCs and two different orgs - the problem is the same.

**Comment by motiko** [comment]
I get it, those components (silverlight, flash..) wont process keys properly. 
I will try and find a fix for it.

**Comment by motiko** [comment]
@AziEI 
Should be fixed in 3.12 please approve
126774da3d76cf6c8d6f8031732a0b41171f69b1
