### ISSUE TITLE
Error 401 - Unauthorised

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [motiko/sfdc-debug-logs#8]
An error 401 appears at the  bottom of the page when I try to load logs.  It appears for a few millis then disappears.

**Comment by motiko** [comment]
I need more information to help with this.
Are you signed into several salesforce instances ?
Do you have custom domain enabled?
Perhaps you can provide me with credentials to some dev org where i can reproduce this?

**Comment by charles-thompson-salesforce-com** [comment]
<oops, try again>
Answers to your questions:

Are you signed into several salesforce instances?
Yes, in different Chrome windows. Is that a problem?

Do you have custom domain enabled? 
Yes. Only for Customer Community, not the main org (where we use myDomain)

Perhaps you can provide me with credentials to some dev org where i can reproduce this?
I’ll be happy to do that once I find one that I can share. You understand. Please hold.

**Comment by motiko** [comment]
> Are you signed into several salesforce instances?
> Yes, in different Chrome windows. Is that a problem?

Not a problem, just trying to figure out what causes this error.
Do you use incognito mode or profiles? Does the error appear for all the windows or for one specific org?
> Do you have custom domain enabled?
> Yes. Only for Customer Community, not the main org (where we use myDomain)

From which org you open the debugger? (i.e. which tab is open when you press Shift+W)

> I’ll be happy to do that once I find one that I can share. You understand. Please hold.

This would be the best option. I of course  understand that this is not easy and sometimes impossible.
I'm waiting 😄

**Comment by motiko** [comment]
@charles-thompson-salesforce-com I believe i found the solution.
Please try with latest (0.7.11) version see if the problem persist.

**Comment by charles-thompson-salesforce-com** [comment]
Thanks!  I'll try it out tomorrow.

**Comment by motiko** [comment]
Just to be clear the solution is not supporting multiple orgs yet ( i will add this next)
Right now it's just a retry mechanism that should hopefully solve the problem i suspect you've encountered.
In case the problem persist please send me detailed reproduction steps.
Including: 
Which type of org you login into (custom domain, lightning e.t.c). 
On which page you activate the extension (VF page, lightning, account, setup or anything else a path part of the url will suffice)

**Comment by charles-thompson-salesforce-com** [comment]
Sure. I need to stick with the rules... one org at a time.

**Comment by motiko** [comment]
No worries the support for multiple orgs will be soon.
Just want to make sure i don't break existing functionalities with it, thank you for your help with it 👍

**Comment by motiko** [comment]
@charles-thompson-salesforce-com Any news?

**Comment by motiko** [comment]
@charles-thompson-salesforce-com I'm closing this issue, feel free to reopen if you encounter the same problem.

**Comment by charles-thompson-salesforce-com** [comment]
Brilliant. Thanks!

**Comment by charles-thompson-salesforce-com** [comment]
I'm sorry I should have responded last week.  Your latest improvements have resolved this issue.  Thank you so much for making the effort!
